### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by paulp** [ornicar/scalex#30]
I'd like to try this out on the compiler sources but I can't get past the "dump" line in the readme.  I've tried various revisions.  I'm on OSX.  Here's what I get after building and publish-localing.

```
scalex:core> run dump /scala/inst/29/lib/scala-library.jar
[info] Running scalex.Cli dump /scala/inst/29/lib/scala-library.jar
* Creating universe...
error: error while loading package, Missing dependency 'class scalex.package', required by ./core/target/scala-2.9.1/classes/scalex/package.class
[error] (run-main) scalex.dump.Compiler$NoCompilerRunException$
scalex.dump.Compiler$NoCompilerRunException$
java.lang.RuntimeException: Nonzero exit code: 1
    at scala.sys.package$.error(package.scala:27)
[error] {file:/r/scalex/scalex/}core/compile:run: Nonzero exit code: 1
[error] Total time: 1 s, completed Jan 31, 2012 7:27:53 AM
```

**Comment by ornicar** [comment]
Hey, the readme was outdated. I've pushed the new version. Now the steps are, from sbt:

1: run dump scala /path/to/scala/source
2: run index
3: run search list map

**Comment by paulp** [comment]
The readme instructions are still needlessly confusing.  If

```
run dump scala /path/to/scala/library
```

is supposed to mean, as I suspect but am still not sure,

```
run dump arbitrary.package /path/to/arbitrary/src
```

then I would suggest writing it more like that, and not using the tokens "scala" or especially "scala library" anywhere in the example.

**Comment by ornicar** [comment]
okay, I will update it. By the way I have only tested it with scala library and scalaz. Other packages are likely to fail due to missing dependencies. I don't know how to solve that yet, but I'm willing to learn and make scalex better.

**Comment by paulp** [comment]
You are correct about it failing if anything else is needed on the
classpath.  (I need ant.jar to compile the compiler source.) I
apologize if I sounded snippy about the readme.

**Comment by ornicar** [comment]
Nah that's fine. In fact I feel greetly honored by the fact you are giving scalex a try.
